### --- USUARIOS ---

### POST registering user
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
content-type: application/json

{
    "username": "Laura", 
    "password": "pass", 
    "role": "admin"
}

### POST Requesting a token
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
content-type: application/json

{"username": "admin", "password": "admin"}

### POST Token refresh
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
content-type: application/json

{"refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDc1ODM5MiwiaWF0IjoxNzQ0NjcxOTkyLCJqdGkiOiJhZWY1Njc1ZDdmOGE0OGE1YTAyNjg1YTQ3MmYxMWEzZSIsInVzZXJfaWQiOjR9.D9ZSGXlBEzjkLZDoWP6VumXTfYoTC_5hb9qf1irDdfg"}

### GET user list
GET http://127.0.0.1:8000/api/users/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs

### 

### --- CURSOS ---

### GET course list
GET http://127.0.0.1:8000/api/courses/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs

### POST create course
POST http://127.0.0.1:8000/api/courses/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs

{"name": "Politica 4", "description": "loreipsumBotomText"}

### GET course detail
GET http://127.0.0.1:8000/api/courses/9 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs

###

### --- ENROLLMENTS ---

### POST enroll course
POST http://127.0.0.1:8000/api/enroll/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzU2NTQwLCJpYXQiOjE3NDQ3NTI5NDAsImp0aSI6IjViZDMwY2RhYmJmMTRhZTliZDExZGEzYzI2M2YzZGEyIiwidXNlcl9pZCI6MX0.BgvP6nwXH4Wqb0ZmlJzi2tlL0V8uBzw2yKLJ8cKm27k

{"course": 1}

### GET enrollments list
GET http://127.0.0.1:8000/api/my-enrollments/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs


###

### --- GRADES ---

### POST grade a student
POST http://127.0.0.1:8000/api/grades/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzY5MjUzLCJpYXQiOjE3NDQ3NjU2NTMsImp0aSI6IjAzNzA1NDllM2Y3NzQ3NWM4MmE4MGY3NGY2ZWRiYWUzIiwidXNlcl9pZCI6MX0.PybiX3D376tVncGxpkGSXfGSTZOnOKX8bdqgfEOP2y0

{
    "enrollment": 12,
    "score": 10,
    "comment": "loreipsum note"
}

### GET grades list for a student (student)
GET http://127.0.0.1:8000/api/my-grades/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs

### GET grades list for a course (instructor)
GET http://127.0.0.1:8000/api/grades/course/2/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzUyODkxLCJpYXQiOjE3NDQ3NDkyOTEsImp0aSI6ImI1MTI5Zjc3NWI1NTQ1Mjc4ZWM1NDkyOWUyODdmMGQxIiwidXNlcl9pZCI6MX0.Yksb0zjm392J1p4irUji_02wzRTGnawBGMD5UTPcnhs
