### --- USUARIOS ---

### POST registering user
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
content-type: application/json

{
    "username": "charly", 
    "password": "pass", 
    "role": "instructor"
}

### POST Requesting a token
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
content-type: application/json

{"username": "admin", "password": "admin"}

### POST Token refresh
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
content-type: application/json

{"refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDc1ODM5MiwiaWF0IjoxNzQ0NjcxOTkyLCJqdGkiOiJhZWY1Njc1ZDdmOGE0OGE1YTAyNjg1YTQ3MmYxMWEzZSIsInVzZXJfaWQiOjR9.D9ZSGXlBEzjkLZDoWP6VumXTfYoTC_5hb9qf1irDdfg"}

### GET user list
GET http://127.0.0.1:8000/api/users/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NjU5NjUyLCJpYXQiOjE3NDQ2NTYwNTIsImp0aSI6IjgyYjI2YTEzNTIyMTRiYjhiOGY1ZGQ4Yzk5NjYwNmFjIiwidXNlcl9pZCI6MX0.jfSGOl0LHdibirF8PIahyxtwxGhtT8fDIh1Q1utLSZc

### 

### --- CURSOS ---

### GET course list
GET http://127.0.0.1:8000/api/courses/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NjY1MzU5LCJpYXQiOjE3NDQ2NjE3NTksImp0aSI6ImY5OTgzOWZlNDZmZDRiNDM5YjgxNmZkM2VhZjYwNTBkIiwidXNlcl9pZCI6NH0.C2w6KZV_TEAe0Bk70dSOmChSiDva6eUQ96iv0qlfYQw

### POST create course
POST http://127.0.0.1:8000/api/courses/create/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NjYyMTE1LCJpYXQiOjE3NDQ2NTg1MTUsImp0aSI6ImNhODFlZDdkZjJmMTRjZDA4MTk5NTZiOGY2NGM4NzU5IiwidXNlcl9pZCI6M30.ccObdnTND3jUFbn2Tcfz0O2gxsyccQXM_cIGUXBUjZ0

{"name": "Robotica", "description": "loreipsum"}

### GET course detail
GET http://127.0.0.1:8000/api/courses/4 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzM4ODM2LCJpYXQiOjE3NDQ3MzUyMzYsImp0aSI6IjljNGU1MGRkYzIzMTQ3MmI4NDI4MzNjZGYwODZlMTY0IiwidXNlcl9pZCI6MX0.x8Y8Hw7VJbpBkOb7q7Jvc6o-J7dVQorSJa_bJJiBZXk

###

### --- ENROLLMENTS ---

### POST enroll course
POST http://127.0.0.1:8000/api/enroll/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzI4MjQzLCJpYXQiOjE3NDQ3MjQ2NDMsImp0aSI6ImExYzk3YWI1MDczMzRlMWU4ZGVjYmMwYmQzZGM5Mjk2IiwidXNlcl9pZCI6NH0.o538AtLHU3l63Y_nUDjkEznMgGmAhq93VS3KCGslW1k

{"course": 2}

### GET enrollments list
GET http://127.0.0.1:8000/api/my-enrollments/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzI3NjQxLCJpYXQiOjE3NDQ3MjQwNDEsImp0aSI6ImM0MzAzYWJlOTUzMzRlZmNiNjQyMmZhYmYyYjRiMWE0IiwidXNlcl9pZCI6NH0.qEFV-co7GDgjxhmlFjfYCpYmhPvLwEFVkZpjcOJ4RhA


###

### --- GRADES ---

### POST grade a student
POST http://127.0.0.1:8000/api/grades/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzM2NzczLCJpYXQiOjE3NDQ3MzMxNzMsImp0aSI6IjJiMGRhZDZiOTgyOTQ2MTY4MmE3ZGRjNDBjYTg0ZDRjIiwidXNlcl9pZCI6Nn0.ngNq0Z45a6eOpU80uIBd8Br_Q2LUS2Y5KtCaAmjHUt4

{
    "enrollment": 7,
    "score": 10,
    "comment": "loreipsum note"
}

### GET grades list for a student (student)
GET http://127.0.0.1:8000/api/my-grades/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzM0NTg3LCJpYXQiOjE3NDQ3MzA5ODcsImp0aSI6ImRhZTI5NzJhN2ExYzQ1MWY4NDA2NGFiODdkY2VhNTFhIiwidXNlcl9pZCI6NH0.mSwl2RdNmePR811ziqbX3lq-gDN_Ho5wUGYZKl2_uGA

### GET grades list for a course (instructor)
GET http://127.0.0.1:8000/api/grades/course/2/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzM4ODM2LCJpYXQiOjE3NDQ3MzUyMzYsImp0aSI6IjljNGU1MGRkYzIzMTQ3MmI4NDI4MzNjZGYwODZlMTY0IiwidXNlcl9pZCI6MX0.x8Y8Hw7VJbpBkOb7q7Jvc6o-J7dVQorSJa_bJJiBZXk
