# Generated by Django 5.2 on 2025-04-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'score')},
        ),
    ]
